import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { requestContext } from "../../common/request-context";
import { FirebaseIdentity, FirebaseService } from "../../database/firebase.service";
import { ThemeActionDto, ThemeCommentDto, ThemeInputDto, ThemeOutputDto, ThemePatchInputDto, ThemeRefineDto } from "./dto";
type R=Record<string,unknown>; const FIELDS=["title","subtitle","scriptures","explanation","pastoralIntroduction","objectives","weeklyDirection","confession","declaration","hashtags","flyerHeadline","designConcept"];
@Injectable() export class ThemesService{constructor(private readonly firebase:FirebaseService){}
 async create(user:FirebaseIdentity,dto:ThemeInputDto){const {organizationId}=await this.active(user,"themes.create"); this.validateInput(dto); const now=new Date().toISOString(), id=randomUUID(), revision=randomUUID(); const theme={id,organizationId,input:dto,currentOutput:this.blank(),approvalState:"draft",comments:[],versions:[],locks:[],auditSummary:[],revision,createdBy:user.uid,createdAt:now,updatedAt:now}; await this.firebase.putDocument(`themes/${id}`,theme); await this.audit(user,organizationId,"theme.create",{themeId:id,revision}); return theme;}
 async get(user:FirebaseIdentity,id:string){return this.theme(user,id,"themes.read")}
 async patchInput(user:FirebaseIdentity,id:string,dto:ThemePatchInputDto){const t=await this.theme(user,id,"themes.update"); if(this.s(t.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The theme is stale.",currentRevision:this.s(t.revision)}); this.validateInput(dto); const revision=randomUUID(), updated={...t,input:{...(t.input as R??{}),...dto},revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.input.save",{themeId:id,revision}); return updated;}
 async generate(user:FirebaseIdentity,id:string,body:Partial<ThemeRefineDto>={}){const t=await this.theme(user,id,"themes.update"); return this.job(user,this.s(t.organizationId),"theme_generate",{themeId:id,sourceRevision:body.sourceRevision??this.s(t.revision)},body.sourceRevision??this.s(t.revision),body.targetFields??FIELDS);}
 async refine(user:FirebaseIdentity,id:string,dto:ThemeRefineDto){const t=await this.theme(user,id,"themes.update"); return this.job(user,this.s(t.organizationId),"theme_refine",{themeId:id,scope:dto.scope,sourceRevision:dto.sourceRevision??this.s(t.revision)},dto.sourceRevision??this.s(t.revision),dto.targetFields??FIELDS);}
 async output(user:FirebaseIdentity,id:string,dto:ThemeOutputDto){const t=await this.theme(user,id,"themes.update"); if(this.s(t.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The theme is stale.",currentRevision:this.s(t.revision)}); if(this.arr(t.locks).length) throw new ForbiddenException({code:"theme_locked",message:"Approved themes require unlock permission."}); const revision=randomUUID(), out={...this.blank(),...(dto.output??{})}, versions=this.arr(t.versions).concat({id:randomUUID(),revision,actor:user.uid,createdAt:new Date().toISOString(),changeSummary:dto.changeSummary??"Theme output updated",approvalState:"draft",output:out}); const updated={...t,currentOutput:out,versions,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.output.save",{themeId:id,revision}); return updated;}
 async preview(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); return {id:t.id,campaignId:(t.input as R)?.campaignId,currentOutput:{...this.blank(),...(t.currentOutput as R??{})},approvalState:t.approvalState};}
 async versions(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); return {versions:this.arr(t.versions)}}
 async comment(user:FirebaseIdentity,id:string,dto:ThemeCommentDto,cid?:string){const t=await this.theme(user,id,"themes.update"); const comments=this.arr(t.comments); const c={id:cid??randomUUID(),body:dto.body,mentions:dto.mentions??[],resolved:dto.resolved===true,actor:user.uid,createdAt:new Date().toISOString(),correlationId:requestContext.getStore()?.correlationId??""}; const updated={...t,comments:cid?comments.map(x=>this.s((x as R).id)===cid?{...(x as R),...c}:x):comments.concat(c),updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.comment",{themeId:id,commentId:c.id}); return c;}
 async action(user:FirebaseIdentity,id:string,action:string,dto:ThemeActionDto){const t=await this.theme(user,id,action==="approve"?"themes.approve":"themes.update"); const revision=randomUUID(), locks=action==="approve"?[{reason:"approved",lockedRevision:dto.revision??this.s(t.revision),actor:user.uid,timestamp:new Date().toISOString()}]:this.arr(t.locks); const updated={...t,approvalState:action,locks,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),`theme.${action}`,{themeId:id,revision,feedback:dto.feedback??""}); return updated;}
 async template(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); const tid=randomUUID(), now=new Date().toISOString(), template={id:tid,organizationId:t.organizationId,sourceThemeId:id,sourceRevision:t.revision,fields:{...this.blank(),...(t.currentOutput as R??{})},createdBy:user.uid,createdAt:now}; await this.firebase.putDocument(`themeTemplates/${tid}`,template); await this.audit(user,this.s(t.organizationId),"theme.template.create",{themeId:id,templateId:tid}); return template;}
 private validateInput(dto:ThemeInputDto){if(!this.s(dto.topic)&&!this.s(dto.spiritualEmphasis)) throw new BadRequestException({code:"theme_validation_failed",message:"A topic or spiritual emphasis is required."}); if(dto.date&&Number.isNaN(Date.parse(dto.date))) throw new BadRequestException({code:"theme_validation_failed",message:"Date is invalid."});}
 private async theme(user:FirebaseIdentity,id:string,perm:string){const t=await this.firebase.getDocument(`themes/${id}`); if(!t) throw new NotFoundException({code:"theme_not_found",message:"Theme not found."}); await this.active(user,perm,this.s(t.organizationId)); return t;}
 private async active(user:FirebaseIdentity,perm:string,org?:string){const u=await this.firebase.getDocument(`users/${user.uid}`); const organizationId=org||this.s(u?.activeOrganizationId); const m=organizationId?await this.firebase.getDocument(`memberships/${organizationId}_${user.uid}`):undefined; if(!organizationId||m?.status!=="ACTIVE"||!this.arr(m.permissions).includes(perm)) throw new ForbiddenException({code:"organization_permission_missing",message:"An active organization membership with permission is required."}); return {organizationId};}
 private blank(){return Object.fromEntries(FIELDS.map(f=>[f, f==="scriptures"||f==="objectives"||f==="weeklyDirection"||f==="hashtags"?[]:""]));} private async job(user:FirebaseIdentity,organizationId:string,type:string,payload:R,sourceRevision:string,targetFields:string[]){const now=new Date().toISOString(),id=randomUUID(); const job={id,organizationId,type,status:"queued",progress:0,retryable:true,cancellationSupported:true,payload,sourceRevision,targetFields,createdBy:user.uid,createdAt:now,updatedAt:now}; await this.firebase.putDocument(`asyncJobs/${id}`,job); await this.audit(user,organizationId,`${type}.queue`,payload); return job;} private async audit(user:FirebaseIdentity,organizationId:string,action:string,summary:R){const id=randomUUID(); await this.firebase.putDocument(`auditEvents/${id}`,{id,correlationId:requestContext.getStore()?.correlationId??"",actor:user.uid,organizationId,resource:action,outcome:"success",summary,createdAt:new Date().toISOString()});} private arr(v:unknown):unknown[]{return Array.isArray(v)?v:[]} private s(v:unknown){return typeof v==="string"?v.trim():"";}}
