import { ConflictException, ForbiddenException, Injectable, Logger, NotFoundException, ServiceUnavailableException, UnprocessableEntityException } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import { requestContext } from "../../common/request-context";
import { FirebaseIdentity, FirebaseService } from "../../database/firebase.service";
import { ThemeActionDto, ThemeCommentDto, ThemeInputDto, ThemeListQueryDto, ThemeOutputDto, ThemePatchInputDto, ThemeRefineDto } from "./dto";
import { ThemeGenerationService } from "./theme-generation.service";
import { ThemeGenerationQueue } from "./theme-generation.queue";
type R=Record<string,unknown>; const FIELDS=["title","subtitle","scriptures","explanation","pastoralIntroduction","objectives","weeklyDirection","confession","declaration","hashtags","flyerHeadline","designConcept"];
@Injectable() export class ThemesService{private readonly logger=new Logger(ThemesService.name); constructor(private readonly firebase:FirebaseService, private readonly generator:ThemeGenerationService, private readonly queue:ThemeGenerationQueue){}
 async list(user:FirebaseIdentity,query:ThemeListQueryDto){const {organizationId}=await this.active(user,"themes.read"); const items=await this.firebase.queryDocuments("themes","organizationId",organizationId,query.sort,query.direction,query.limit); return {items,nextCursor:null};}
 async create(user:FirebaseIdentity,dto:ThemeInputDto){const {organizationId}=await this.active(user,"themes.create"); const input=this.normalizeInput(dto); this.validateInput(input); const now=new Date().toISOString(), id=randomUUID(), revision=randomUUID(); const theme={id,organizationId,input,currentOutput:this.blank(),approvalState:"draft",comments:[],versions:[],locks:[],auditSummary:[],revision,createdBy:user.uid,createdAt:now,updatedAt:now}; await this.firebase.putDocument(`themes/${id}`,theme); await this.audit(user,organizationId,"theme.create",{themeId:id,revision}); return theme;}
 async get(user:FirebaseIdentity,id:string){return this.theme(user,id,"themes.read")}
 async patchInput(user:FirebaseIdentity,id:string,dto:ThemePatchInputDto){const t=await this.theme(user,id,"themes.update"); if(this.s(t.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The theme is stale.",currentRevision:this.s(t.revision)}); this.validateInput(dto); const revision=randomUUID(), updated={...t,input:{...(t.input as R??{}),...dto},revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.input.save",{themeId:id,revision}); return updated;}
 async generate(user:FirebaseIdentity,id:string,body:Partial<ThemeRefineDto>={},idempotencyKey?:string){const t=await this.theme(user,id,"themes.update"); return this.queueGeneration(user,t,id,"theme_generate",body.sourceRevision??this.s(t.revision),body.targetFields??FIELDS,undefined,idempotencyKey);}
 async refine(user:FirebaseIdentity,id:string,dto:ThemeRefineDto,idempotencyKey?:string){const t=await this.theme(user,id,"themes.update"); return this.queueGeneration(user,t,id,"theme_refine",dto.sourceRevision??this.s(t.revision),dto.targetFields??FIELDS,dto.scope,idempotencyKey);}
 async output(user:FirebaseIdentity,id:string,dto:ThemeOutputDto){const t=await this.theme(user,id,"themes.update"); if(this.s(t.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The theme is stale.",currentRevision:this.s(t.revision)}); if(this.arr(t.locks).length) throw new ForbiddenException({code:"theme_locked",message:"Approved themes require unlock permission."}); const revision=randomUUID(), out={...this.blank(),...(dto.output??{})}, versions=this.arr(t.versions).concat({id:randomUUID(),revision,actor:user.uid,createdAt:new Date().toISOString(),changeSummary:dto.changeSummary??"Theme output updated",approvalState:"draft",output:out}); const updated={...t,currentOutput:out,versions,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.output.save",{themeId:id,revision}); return updated;}
 async preview(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); return {id:t.id,campaignId:(t.input as R)?.campaignId,currentOutput:{...this.blank(),...(t.currentOutput as R??{})},approvalState:t.approvalState};}
 async versions(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); return {versions:this.arr(t.versions)}}
 async comment(user:FirebaseIdentity,id:string,dto:ThemeCommentDto,cid?:string){const t=await this.theme(user,id,"themes.update"); const comments=this.arr(t.comments); const c={id:cid??randomUUID(),body:dto.body,mentions:dto.mentions??[],resolved:dto.resolved===true,actor:user.uid,createdAt:new Date().toISOString(),correlationId:requestContext.getStore()?.correlationId??""}; const updated={...t,comments:cid?comments.map(x=>this.s((x as R).id)===cid?{...(x as R),...c}:x):comments.concat(c),updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),"theme.comment",{themeId:id,commentId:c.id}); return c;}
 async action(user:FirebaseIdentity,id:string,action:string,dto:ThemeActionDto){const t=await this.theme(user,id,action==="approve"?"themes.approve":"themes.update"); const revision=randomUUID(), locks=action==="approve"?[{reason:"approved",lockedRevision:dto.revision??this.s(t.revision),actor:user.uid,timestamp:new Date().toISOString()}]:this.arr(t.locks); const updated={...t,approvalState:action,locks,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`themes/${id}`,updated); await this.audit(user,this.s(t.organizationId),`theme.${action}`,{themeId:id,revision,feedback:dto.feedback??""}); return updated;}
 async template(user:FirebaseIdentity,id:string){const t=await this.theme(user,id,"themes.read"); const tid=randomUUID(), now=new Date().toISOString(), template={id:tid,organizationId:t.organizationId,sourceThemeId:id,sourceRevision:t.revision,fields:{...this.blank(),...(t.currentOutput as R??{})},createdBy:user.uid,createdAt:now}; await this.firebase.putDocument(`themeTemplates/${tid}`,template); await this.audit(user,this.s(t.organizationId),"theme.template.create",{themeId:id,templateId:tid}); return template;}
 private validateInput(dto:ThemeInputDto){if(!this.s(dto.topic)&&!this.s(dto.spiritualEmphasis)) throw new UnprocessableEntityException({code:"theme_validation_failed",message:"A topic or spiritual emphasis is required."}); if(dto.date&&Number.isNaN(Date.parse(dto.date))) throw new UnprocessableEntityException({code:"theme_validation_failed",message:"Date is invalid."});}
 private normalizeInput(dto:ThemeInputDto):ThemeInputDto {const brief=dto.brief??{}; const scripture=this.s(brief.main_scripture); return {...dto,date:this.s(dto.date)||this.s(brief.month_and_year)||undefined,topic:this.s(dto.topic)||this.s(brief.topic)||undefined,spiritualEmphasis:this.s(dto.spiritualEmphasis)||this.s(brief.spiritual_emphasis)||undefined,pastorNotes:this.s(dto.pastorNotes)||this.s(brief.pastor_notes)||undefined,tone:this.s(dto.tone)||this.s(brief.tone)||undefined,audience:this.s(dto.audience)||this.s(brief.audience)||undefined,bibleTranslation:this.s(dto.bibleTranslation)||this.s(brief.bible_translation)||undefined,scriptures:dto.scriptures??(scripture?[scripture]:undefined)};}
 private async theme(user:FirebaseIdentity,id:string,perm:string){const t=await this.firebase.getDocument(`themes/${id}`); if(!t) throw new NotFoundException({code:"theme_not_found",message:"Theme not found."}); await this.active(user,perm,this.s(t.organizationId)); return t;}
 private async active(user:FirebaseIdentity,perm:string,org?:string){const u=await this.firebase.getDocument(`users/${user.uid}`); const organizationId=org||this.s(u?.activeOrganizationId); const m=organizationId?await this.firebase.getDocument(`memberships/${organizationId}_${user.uid}`):undefined; const permissions=this.arr(m?.permissions); const legacyPermission=["themes.create","themes.update"].includes(perm)?"themes.write":perm; if(!organizationId||m?.status!=="ACTIVE"||(!permissions.includes(perm)&&!permissions.includes(legacyPermission))) throw new ForbiddenException({code:"organization_permission_missing",message:"An active organization membership with permission is required."}); return {organizationId};}
 private async queueGeneration(user:FirebaseIdentity,t:R,themeId:string,type:string,sourceRevision:string,targetFields:string[],scope?:string,idempotencyKey?:string){
  const requestStartedAt=Date.now(),validationStartedAt=Date.now();
  this.validateInput((t.input as ThemeInputDto) ?? {});
  if(sourceRevision!==this.s(t.revision)) throw new ConflictException({code:"theme_revision_conflict",message:"The theme is stale.",currentRevision:this.s(t.revision)});
  const fields=targetFields.filter(field=>FIELDS.includes(field)); if(!fields.length) throw new UnprocessableEntityException({code:"theme_validation_failed",message:"At least one valid target field is required."});
  const validationMs=Date.now()-validationStartedAt;
  const organizationId=this.s(t.organizationId),payload={themeId,sourceRevision,...(scope?{scope}:{})},now=new Date().toISOString();
  const suppliedKey=this.s(idempotencyKey); const resolvedKey=suppliedKey||createHash("sha256").update([organizationId,themeId,type,sourceRevision].join("\0")).digest("hex"); const jobId=this.stableJobId(organizationId,themeId,type,sourceRevision,resolvedKey);
  {const existing=await this.firebase.getDocument(`asyncJobs/${jobId}`); if(existing)return this.publicJob(existing);}
  const correlationId=requestContext.getStore()?.correlationId??randomUUID();
  const job={id:jobId,organizationId,themeId,operation:type,type,status:"pending_enqueue",progress:0,message:"Preparing to queue",retryable:true,cancellationSupported:true,payload,sourceRevision,targetFields:fields,idempotencyKey:resolvedKey,correlationId,attemptCount:0,maxAttempts:3,provider:"openai",providerModel:"",createdBy:user.uid,createdAt:now,updatedAt:now};
  const durableStartedAt=Date.now(); try {
   await this.firebase.putDocument(`asyncJobs/${jobId}`,job);
  } catch {
   throw new ServiceUnavailableException({code:"generation_queue_unavailable",detail:"Theme generation cannot be queued right now. Please retry shortly.",correlationId,validation:[]});
  }
  const durableJobCreationMs=Date.now()-durableStartedAt,queuePublishStartedAt=Date.now();
  let queuedJob:R;
  try { const queueJobId=await this.queue.publish({jobId,correlationId,organizationId,themeId,sourceRevision}); const queuedAt=new Date().toISOString(); queuedJob={...job,status:"queued",progress:0,message:"Queued",queueJobId,queuedAt,enqueuedAt:queuedAt,updatedAt:queuedAt}; await this.firebase.putDocument(`asyncJobs/${jobId}`,queuedJob); }
  catch(error){const failedAt=new Date().toISOString(); try {await this.firebase.putDocument(`asyncJobs/${jobId}`,{...job,status:"enqueue_failed",retryable:true,safeErrorCode:"generation_queue_unavailable",safeErrorDetail:"Theme generation cannot be queued right now. Please retry shortly.",failedAt,updatedAt:failedAt,correlationId});} catch {this.logger.error({event:"theme.generation.enqueue_failure_persistence_failed",correlationId,durableJobId:jobId},"Could not persist queue failure state");} throw error;}
  try {await this.audit(user,organizationId,`${type}.queued`,payload);} catch(error){this.logger.error({jobId,organizationId,type,error:error instanceof Error?error.message:"audit_write_failed"},"Theme generation audit write failed");}
  this.logger.log({event:"theme.generation.request_completed",correlationId,durableJobId:jobId,validationMs,durableJobCreationMs,queuePublishMs:Date.now()-queuePublishStartedAt,totalMs:Date.now()-requestStartedAt},"Theme generation request queued"); return this.publicJob(queuedJob);
 }
 private stableJobId(organizationId:string,themeId:string,type:string,revision:string,key:string){return createHash("sha256").update([organizationId,themeId,type,revision,key].join("\0")).digest("hex").slice(0,32);}
 private publicJob(job:R){return {id:this.s(job.id),status:this.s(job.status),progress:Math.max(0,Math.min(100,Number(job.progress)||0)),retryable:job.retryable===true,cancellationSupported:job.cancellationSupported===true,sourceRevision:this.s(job.sourceRevision),targetFields:this.arr(job.targetFields).filter((field):field is string=>typeof field==="string"),createdAt:this.s(job.createdAt),updatedAt:this.s(job.updatedAt)};}
 private blank(){return Object.fromEntries(FIELDS.map(f=>[f, f==="scriptures"||f==="objectives"||f==="weeklyDirection"||f==="hashtags"?[]:""]));} private async audit(user:FirebaseIdentity,organizationId:string,action:string,summary:R){const id=randomUUID(); await this.firebase.putDocument(`auditEvents/${id}`,{id,correlationId:requestContext.getStore()?.correlationId??"",actor:user.uid,organizationId,resource:action,outcome:"success",summary,createdAt:new Date().toISOString()});} private arr(v:unknown):unknown[]{return Array.isArray(v)?v:[]} private s(v:unknown){return typeof v==="string"?v.trim():"";}}
