import { BadRequestException, ConflictException, ForbiddenException, Injectable, InternalServerErrorException, NotFoundException, Optional } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import { requestContext } from "../../common/request-context";
import { FirebaseIdentity, FirebaseService } from "../../database/firebase.service";
import { CampaignDraftDto, CampaignWizardDto, CreateCampaignDto, DuplicateCampaignDto, GenerateDto, SectionActionDto, SectionMutationDto } from "./dto";
import { CampaignStatus } from "../../database/firestore";
import { ApprovalWorkflowService } from "../workflows/approval-workflow.service";
type R = Record<string, unknown>; const SCOPES = ["theme","pastoral-introduction","objectives","declaration","prayers","sermon-series","flyer-plan","social-plan","video-plan","publishing-calendar"];
@Injectable()
export class CampaignsService { constructor(private readonly firebase: FirebaseService, @Optional() private readonly approvals?: ApprovalWorkflowService) {}
 async createDraft(user: FirebaseIdentity,dto:CampaignDraftDto){return this.createBase(user,dto.month,dto.year,{spiritualFocus:"",scriptures:[],tone:"",prayerQuantity:1,bibleTranslation:""}); }
 async create(user: FirebaseIdentity,dto:CreateCampaignDto){const [year,month]=this.parseMonthInput(dto.month); const scriptures=dto.scriptures??(dto.scripture?[dto.scripture]:[]); return this.createBase(user,month,year,{spiritualFocus:dto.spiritualFocus??dto.focus??"",scriptures,tone:dto.tone??"",prayerQuantity:dto.prayerQuantity??1,bibleTranslation:dto.bibleTranslation??""}); }
 async get(user:FirebaseIdentity,id:string){const c=await this.campaign(user,id,"campaigns.read"); return c;}
 async wizard(user:FirebaseIdentity,id:string,dto:CampaignWizardDto){const c=await this.campaign(user,id,"campaigns.update"); if(this.s(c.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The campaign is stale.",currentRevision:this.s(c.revision)}); this.validateMonth(Number(c.month),Number(c.year)); const revision=randomUUID(), updated={...c,...dto,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`campaigns/${id}`,updated); await this.audit(user,this.s(c.organizationId),"campaign.save",{campaignId:id,revision}); return updated;}
 async duplicate(user:FirebaseIdentity,id:string,dto:DuplicateCampaignDto){const c=await this.campaign(user,id,"campaigns.create"); this.validateMonth(dto.month,dto.year); const now=new Date().toISOString(), nid=randomUUID(), revision=randomUUID(); const copy={...c,id:nid,month:dto.month,year:dto.year,monthLabel:this.monthLabel(dto.month,dto.year),status:CampaignStatus.Draft,ownerId:user.uid,revision,createdAt:now,updatedAt:now,archivedAt:null,versions:[],locks:[],auditEvents:[],sourceCampaignId:id,sourceRevision:c.revision}; await this.firebase.putDocument(`campaigns/${nid}`,copy); await this.audit(user,this.s(c.organizationId),"campaign.duplicate",{campaignId:nid,sourceCampaignId:id,revision}); return copy;}
 async archive(user:FirebaseIdentity,id:string){return this.lifecycle(user,id,"campaigns.update","archive",{archivedAt:new Date().toISOString(),status:CampaignStatus.Archived});} async restore(user:FirebaseIdentity,id:string){return this.lifecycle(user,id,"campaigns.update","restore",{archivedAt:null,status:CampaignStatus.Draft});}
 async generate(user:FirebaseIdentity,id:string,dto:GenerateDto,scope?:string){const c=await this.campaign(user,id,"campaigns.generate"); if(scope && !SCOPES.includes(scope)) throw new BadRequestException({code:"invalid_section_scope",message:"Section scope is not supported."}); const sourceRevision=dto.sourceRevision??dto.revision??this.s(c.revision); return this.job(user,this.s(c.organizationId),scope?"campaign_section_generate":"campaign_generate",{campaignId:id,scope,sourceRevision},sourceRevision,scope);}
 async mutateSection(user:FirebaseIdentity,id:string,scope:string,dto:SectionMutationDto){const c=await this.campaign(user,id,"campaigns.update"); this.assertScope(scope); if(this.s(c.revision)!==dto.revision) throw new ConflictException({code:"revision_conflict",message:"The campaign is stale.",currentRevision:this.s(c.revision)}); if(this.locked(c,scope)) throw new ForbiddenException({code:"section_locked",message:"Approved locked sections require unlock permission."}); const revision=randomUUID(), versions=this.arr(c.versions).concat({id:randomUUID(),scope,revision,actor:user.uid,createdAt:new Date().toISOString(),changeSummary:dto.changeSummary??"Section updated",approvalState:"draft",content:dto.content??{}}); const updated={...c,revision,versions,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`campaigns/${id}`,updated); await this.audit(user,this.s(c.organizationId),"campaign.section.save",{campaignId:id,scope,revision}); return updated;}
 async versions(user:FirebaseIdentity,id:string,scope:string){const c=await this.campaign(user,id,"campaigns.read"); this.assertScope(scope); return {versions:this.arr(c.versions).filter(v=>this.s((v as R).scope)===scope)};}
 async sectionAction(user:FirebaseIdentity,id:string,scope:string,action:string,dto:SectionActionDto){const c=await this.campaign(user,id,action==="submit-review"?"campaigns.update":action==="unlock"?"campaigns.unlock":"campaigns.approve"); this.assertScope(scope); const current=this.arr(c.versions).filter(v=>this.s((v as R).scope)===scope).at(-1) as R|undefined; if(action==="submit-review"){if(!current) throw new ConflictException({code:"campaign_section_version_required",message:"Save or generate this section before submitting for review."}); if(!this.approvals) throw new InternalServerErrorException({code:"approval_pipeline_unavailable",message:"Approval persistence is unavailable."}); const resource={...c,id:`${id}:${scope}`}; const approval=await this.approvals.submit(user,resource,"campaign_section",this.s(current.id),this.s(current.revision),this.s((dto as R).reviewerUserId)); const updated={...c,sectionApprovalStates:{...((c.sectionApprovalStates as R)??{}),[scope]:"pending_approval"},updatedAt:new Date().toISOString()}; try{await this.firebase.putDocument(`campaigns/${id}`,updated);}catch(error){await this.approvals.compensateFailedSubmission(this.s(c.organizationId),this.s(approval.id));throw error;} await this.audit(user,this.s(c.organizationId),"campaign.section.submitted_for_review",{campaignId:id,scope,approvalId:approval.id,versionId:current.id}); return {campaign:updated,approval};} const approval=await this.approvals?.current(this.s(c.organizationId),"campaign_section",`${id}:${scope}`); if(!approval) throw new ConflictException({code:"active_approval_required",message:"No active approval exists for this campaign section."}); const target=action==="request-changes"?"changes_requested":action==="approve"?"approved":"rejected"; await this.approvals?.transition(this.s(approval.id),target,user,dto.reason??dto.feedback); const revision=randomUUID(), locks=action==="approve"?this.arr(c.locks).concat({scope,lockReason:"approved",lockedRevision:dto.revision??this.s(c.revision),actor:user.uid,timestamp:new Date().toISOString()}):action==="unlock"?this.arr(c.locks).filter(v=>this.s((v as R).scope)!==scope):this.arr(c.locks); const updated={...c,revision,locks,sectionApprovalStates:{...((c.sectionApprovalStates as R)??{}),[scope]:target},updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`campaigns/${id}`,updated); await this.audit(user,this.s(c.organizationId),`campaign.section.${action}`,{campaignId:id,scope,revision,approvalId:approval.id,summary:dto.reason??dto.feedback??action}); return updated;}
 private async createBase(user: FirebaseIdentity,month:number,year:number,values:Pick<CampaignWizardDto,"spiritualFocus"|"scriptures"|"tone"|"prayerQuantity"|"bibleTranslation">){const {organizationId}=await this.active(user,"campaigns.create"); this.validateMonth(month,year); const now=new Date().toISOString(), id=randomUUID(), revision=randomUUID(); const campaign={id,organizationId,month,year,monthLabel:this.monthLabel(month,year),spiritualFocus:values.spiritualFocus??"",scriptures:values.scriptures??[],sundays:[],events:[],tone:values.tone??"",prayerQuantity:values.prayerQuantity??1,bibleTranslation:values.bibleTranslation??"",status:CampaignStatus.Draft,ownerId:user.uid,createdAt:now,updatedAt:now,revision,archivedAt:null,sections:[],assignments:[],versions:[],locks:[],auditEvents:[]}; await this.firebase.putDocument(`campaigns/${id}`,campaign); await this.audit(user,organizationId,"campaign.create",{campaignId:id,revision}); return campaign; }
 private async lifecycle(user:FirebaseIdentity,id:string,perm:string,action:string,patch:R){const c=await this.campaign(user,id,perm); const revision=randomUUID(), updated={...c,...patch,revision,updatedAt:new Date().toISOString()}; await this.firebase.putDocument(`campaigns/${id}`,updated); await this.audit(user,this.s(c.organizationId),`campaign.${action}`,{campaignId:id,revision}); return updated;}
 private async campaign(user:FirebaseIdentity,id:string,perm:string){const c=await this.firebase.getDocument(`campaigns/${id}`); if(!c) throw new NotFoundException({code:"campaign_not_found",message:"Campaign not found."}); await this.active(user,perm,this.s(c.organizationId)); return c;}
 private async active(user:FirebaseIdentity,perm:string,org?:string){const u=await this.firebase.getDocument(`users/${user.uid}`); const organizationId=org||this.s(u?.activeOrganizationId); const m=organizationId?await this.firebase.getDocument(`memberships/${organizationId}_${user.uid}`):undefined; if(!organizationId||m?.status!=="ACTIVE"||!this.hasPermission(m,perm)) throw new ForbiddenException({code:"organization_permission_missing",message:"An active organization membership with permission is required."}); return {organizationId};}
 private hasPermission(membership:R|undefined,permission:string){const values=this.arr(membership?.permissions).map((value)=>this.s(value)); const role=this.s(membership?.role); return values.includes(permission)||values.includes("campaigns.write")||values.includes("admin")||["ChurchAdministrator","SuperAdministrator"].includes(role);}
 private parseMonthInput(month:string):[number,number]{const match=/^(\d{4})-(\d{2})$/.exec(month); if(!match) throw new BadRequestException({code:"campaign_validation_failed",message:"Month must use YYYY-MM format."}); return [Number(match[1]),Number(match[2])];}
 private validateMonth(month:number,year:number){if(month<1||month>12||year<2020||year>2100) throw new BadRequestException({code:"campaign_validation_failed",message:"Invalid campaign month or year."});}
 private monthLabel(m:number,y:number){return new Date(Date.UTC(y,m-1,1)).toLocaleString("en-US",{month:"long",year:"numeric",timeZone:"UTC"});} private assertScope(s:string){if(!SCOPES.includes(s)) throw new BadRequestException({code:"invalid_section_scope",message:"Section scope is not supported."});} private locked(c:R,scope:string){return this.arr(c.locks).some(v=>this.s((v as R).scope)===scope);} private async job(user:FirebaseIdentity,organizationId:string,type:string,payload:R,sourceRevision:string,scope?:string){const now=new Date().toISOString(),id=randomUUID(); const job={id,organizationId,type,status:"queued",progress:0,retryable:true,cancellationSupported:true,payload,sourceRevision,currentSection:scope??"",createdBy:user.uid,createdAt:now,updatedAt:now}; await this.firebase.putDocument(`asyncJobs/${id}`,job); await this.audit(user,organizationId,`${type}.queue`,payload); return job;} private async audit(user:FirebaseIdentity,organizationId:string,action:string,summary:R){const id=randomUUID(); await this.firebase.putDocument(`auditEvents/${id}`,{id,correlationId:requestContext.getStore()?.correlationId??"",actor:user.uid,organizationId,resource:action,outcome:"success",summary,createdAt:new Date().toISOString()});} private arr(v:unknown):unknown[]{return Array.isArray(v)?v:[]} private s(v:unknown){return typeof v==="string"?v.trim():"";}}
